### ISSUE TITLE
Google Podcast Link doesn't Render Correctly on Player

### ISSUE THREAD

**Issue by ruess** [podlove/podlove-web-player-wp-plugin#46]
Hi there,

Incredible new player first of all! Love the new direction and the added functionality - Well done!

One strange issue: while I've configured Apple, Stitcher and Spotify correctly for my podcast using the corresponding IDs from those services for my podcast, I cannot seem to get Google Podcast to arrive at my podcast when I click it from the player. Even stranger, the ID seems to different in the front-end player from the ID I've added to the settings. For instance, the podcast ID I've added to my settings in the box is:
aHR0cHM6Ly9jYWZldHJ1dGguY29tL2ZlZWQvbTRhLw

I save it and that ID remains the same in the settings area, however, when I go to the frontend player and click on the Google Podcast link after clicking the Subscribe button, it sends me to a different link instead:
https://podcasts.google.com/?feed=allXWmxkSEoxZEdndVkyOXRMMlpsWldRdmJUUmhMdw==

The two don't matchup in any way that I can see. Also, the resulting Google Podcasts page displays the following error: "This podcast is not available or not yet published" (instead of showing the correct podcast page)

Any idea what might be going on?

Thanks!

[Version 5.2.8]

**Comment by alexander-heimbuch** [comment]
Hey,

the player tries to be smart and encodes your feed to base64. So for Google it is enough to pass in your feed. Since this issue was reported several times I will adapt the configuration :)
