### ISSUE TITLE
Player starts last episode after initial episode has finished

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player-wp-plugin#57]
I just found the following:

1. Play an episode from my website [https://GameTalk.FM](https://GameTalk.FM).

2. Let it finish. (Skipping to the end works to speed this up, even though everyone should listen the whole thing for obvious reasons.)
![image](https://user-images.githubusercontent.com/11300164/98124495-8ee0ab80-1eb3-11eb-9e3d-94ca3a9a645b.png)

3. The player will automatically start the last (current episode number -1) episode. In fact, the player will be replaced by the player of that other episode (without the sharing tab).
![image](https://user-images.githubusercontent.com/11300164/98124280-445f2f00-1eb3-11eb-80db-872b2bfdf5e3.png)

I expect the player to stop playing after an episode has finished. Is this a bug or a feature?

I'm on Windows 10, Microsoft Edge Version 86.0.622.61.

```
Website                    https://GameTalk.FM
PHP Version                7.4.11
WordPress Version          5.5.3
WordPress Theme            Joeys Twenty Fifteen Child v2.1.4
Active Plugins             
           - Akismet Anti-Spam v4.1.7
           - Classic Editor v1.6
           - Limit Login Attempts v1.7.1
           - Podlove Podcast Publisher v2.11.4
           - Podlove Web Player v5.2.9
           - Yoast SEO v15.2.1
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.11.4
Web Player Version         player_v5
Twig Version               1.42.2
Monolog Version            1
open_basedir               ok
curl Version               7.71.0
iconv                      available
simplexml                  ok
max_execution_time         50
upload_max_filesize        100M
memory_limit               256M
disable_classes            
disable_functions          exec, shell_exec, system, dl, passthru, proc_open, proc_close
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://GameTalk.FM/feed/mp3/
  - m4a    audio/mp4        https://GameTalk.FM/feed/m4a/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!
```

**Comment by Inrumpo** [comment]
I've now updated the player plugin to version `5.3.1` and the publisher plugin to version `3.1.0`. The behaviour described above still persists.

**Comment by alexander-heimbuch** [comment]
Sorry for the late response. This should be a feature but not very transparent if you don't use the related episodes :/ Will investigate!

**Comment by alexander-heimbuch** [comment]
With version v5.4.1 you should be able to disable the related episodes feature.
