### ISSUE TITLE
Missing Semicolon in cache.js breaks bundeled code

### ISSUE THREAD

**Issue by maltekiessling** [podlove/podlove-web-player-wp-plugin#69]
I'm using Podlove Web Player 5.4.4 with Swift Performance Lite 2.1.5
Swift Performance Lite is bundeling all javascript files and the missing semicolon at the end of the /js/cache.js file is breaking the following code.

![image](https://user-images.githubusercontent.com/30420110/101877658-a421b780-3b8e-11eb-9706-ea7d2361b778.png)

**Comment by alexander-heimbuch** [comment]
Thanks for the report and investigation, will add it with the next release.

**Comment by alexander-heimbuch** [comment]
should be fixed with v5.4.5
