### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by ger82** [podlove/podlove-web-player-wp-plugin#72]
I get 2 diverent Warning:

PHP Warning:  array_replace_recursive(): Argument #1 is not an array in /wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 285

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-embed-data.php on line 124

**Comment by alexander-heimbuch** [comment]
Should be fixed with v5.4.5

**Comment by ger82** [comment]
Sorry but the issues still exists.
